// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoeZilla.Data;

#nullable disable

namespace ShoeZilla.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251224101055_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShoeZilla.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Men"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Women"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kids"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Joggers"
                        });
                });

            modelBuilder.Entity("ShoeZilla.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ShoeZilla.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ShoeZilla.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Premium Classic Oxford designed for style and comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605733160314-4fc7dac4bb16?w=500&q=80",
                            Name = "Classic Oxford",
                            Price = 83.99m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Premium Urban Boot designed for style and comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1668069226492-508742b03147?w=500&q=80",
                            Name = "Urban Boot",
                            Price = 85.99m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Premium Formal Derby designed for style and comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1614253429340-98120bd6d753?w=500&q=80",
                            Name = "Formal Derby",
                            Price = 87.99m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Premium City Loafer designed for style and comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=500&q=80",
                            Name = "City Loafer",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Premium Weekend Sneaker designed for style and comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1617689563472-c66428e83d17?w=500&q=80",
                            Name = "Weekend Sneaker",
                            Price = 91.99m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Premium Trail Hiker designed for style and comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605733160314-4fc7dac4bb16?w=500&q=80",
                            Name = "Trail Hiker",
                            Price = 93.99m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Premium Business Brogue designed for style and comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1668069226492-508742b03147?w=500&q=80",
                            Name = "Business Brogue",
                            Price = 95.99m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "Premium Summer Slip-on designed for style and comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1614253429340-98120bd6d753?w=500&q=80",
                            Name = "Summer Slip-on",
                            Price = 97.99m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "Premium Winter Trekker designed for style and comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=500&q=80",
                            Name = "Winter Trekker",
                            Price = 99.99m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Description = "Premium Sport Trainer designed for style and comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1617689563472-c66428e83d17?w=500&q=80",
                            Name = "Sport Trainer",
                            Price = 101.99m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Description = "Premium Canvas Classic designed for style and comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605733160314-4fc7dac4bb16?w=500&q=80",
                            Name = "Canvas Classic",
                            Price = 103.99m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Description = "Premium Suede Chukka designed for style and comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1668069226492-508742b03147?w=500&q=80",
                            Name = "Suede Chukka",
                            Price = 105.99m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            Description = "Premium Leather Monk designed for style and comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1614253429340-98120bd6d753?w=500&q=80",
                            Name = "Leather Monk",
                            Price = 107.99m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            Description = "Premium Chelsea Boot designed for style and comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=500&q=80",
                            Name = "Chelsea Boot",
                            Price = 109.99m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            Description = "Premium Driving Shoe designed for style and comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1617689563472-c66428e83d17?w=500&q=80",
                            Name = "Driving Shoe",
                            Price = 111.99m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            Description = "Premium Retro High-top designed for style and comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605733160314-4fc7dac4bb16?w=500&q=80",
                            Name = "Retro High-top",
                            Price = 113.99m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            Description = "Premium Modern Runner designed for style and comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1668069226492-508742b03147?w=500&q=80",
                            Name = "Modern Runner",
                            Price = 115.99m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            Description = "Premium Minimalist Sneaker designed for style and comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1614253429340-98120bd6d753?w=500&q=80",
                            Name = "Minimalist Sneaker",
                            Price = 117.99m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            Description = "Premium Desert Boot designed for style and comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=500&q=80",
                            Name = "Desert Boot",
                            Price = 119.99m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            Description = "Premium Yacht Deck Shoe designed for style and comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1617689563472-c66428e83d17?w=500&q=80",
                            Name = "Yacht Deck Shoe",
                            Price = 121.99m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            Description = "Elegant Classic Pump perfect for any occasion.",
                            ImageUrl = "https://images.unsplash.com/photo-1539722833765-af2db79db72d?w=500&q=80",
                            Name = "Classic Pump",
                            Price = 92.99m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            Description = "Elegant Summer Sandal perfect for any occasion.",
                            ImageUrl = "https://images.unsplash.com/photo-1554062614-6da4fa67725a?w=500&q=80",
                            Name = "Summer Sandal",
                            Price = 94.49m
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            Description = "Elegant Ankle Boot perfect for any occasion.",
                            ImageUrl = "https://images.unsplash.com/photo-1605733513549-de9b150bd70d?w=500&q=80",
                            Name = "Ankle Boot",
                            Price = 95.99m
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 2,
                            Description = "Elegant Ballet Flat perfect for any occasion.",
                            ImageUrl = "https://images.unsplash.com/photo-1534653299134-96a171b61581?w=500&q=80",
                            Name = "Ballet Flat",
                            Price = 97.49m
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 2,
                            Description = "Elegant Running Trainer perfect for any occasion.",
                            ImageUrl = "https://images.unsplash.com/photo-1553808373-b2c5b7ddb117?w=500&q=80",
                            Name = "Running Trainer",
                            Price = 98.99m
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 2,
                            Description = "Elegant Platform Sneaker perfect for any occasion.",
                            ImageUrl = "https://images.unsplash.com/photo-1539722833765-af2db79db72d?w=500&q=80",
                            Name = "Platform Sneaker",
                            Price = 100.49m
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 2,
                            Description = "Elegant Leather Loafer perfect for any occasion.",
                            ImageUrl = "https://images.unsplash.com/photo-1554062614-6da4fa67725a?w=500&q=80",
                            Name = "Leather Loafer",
                            Price = 101.99m
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 2,
                            Description = "Elegant Strappy Heel perfect for any occasion.",
                            ImageUrl = "https://images.unsplash.com/photo-1605733513549-de9b150bd70d?w=500&q=80",
                            Name = "Strappy Heel",
                            Price = 103.49m
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 2,
                            Description = "Elegant Winter Bootie perfect for any occasion.",
                            ImageUrl = "https://images.unsplash.com/photo-1534653299134-96a171b61581?w=500&q=80",
                            Name = "Winter Bootie",
                            Price = 104.99m
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 2,
                            Description = "Elegant Espadrille Wedge perfect for any occasion.",
                            ImageUrl = "https://images.unsplash.com/photo-1553808373-b2c5b7ddb117?w=500&q=80",
                            Name = "Espadrille Wedge",
                            Price = 106.49m
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 2,
                            Description = "Elegant Canvas Slip-on perfect for any occasion.",
                            ImageUrl = "https://images.unsplash.com/photo-1539722833765-af2db79db72d?w=500&q=80",
                            Name = "Canvas Slip-on",
                            Price = 107.99m
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 2,
                            Description = "Elegant Suede Moccasin perfect for any occasion.",
                            ImageUrl = "https://images.unsplash.com/photo-1554062614-6da4fa67725a?w=500&q=80",
                            Name = "Suede Moccasin",
                            Price = 109.49m
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 2,
                            Description = "Elegant Statement Heel perfect for any occasion.",
                            ImageUrl = "https://images.unsplash.com/photo-1605733513549-de9b150bd70d?w=500&q=80",
                            Name = "Statement Heel",
                            Price = 110.99m
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 2,
                            Description = "Elegant Chelsea Boot perfect for any occasion.",
                            ImageUrl = "https://images.unsplash.com/photo-1534653299134-96a171b61581?w=500&q=80",
                            Name = "Chelsea Boot",
                            Price = 112.49m
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 2,
                            Description = "Elegant Walking Shoe perfect for any occasion.",
                            ImageUrl = "https://images.unsplash.com/photo-1553808373-b2c5b7ddb117?w=500&q=80",
                            Name = "Walking Shoe",
                            Price = 113.99m
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 2,
                            Description = "Elegant Fashion Sneaker perfect for any occasion.",
                            ImageUrl = "https://images.unsplash.com/photo-1539722833765-af2db79db72d?w=500&q=80",
                            Name = "Fashion Sneaker",
                            Price = 115.49m
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 2,
                            Description = "Elegant Mule Slide perfect for any occasion.",
                            ImageUrl = "https://images.unsplash.com/photo-1554062614-6da4fa67725a?w=500&q=80",
                            Name = "Mule Slide",
                            Price = 116.99m
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 2,
                            Description = "Elegant Knee High Boot perfect for any occasion.",
                            ImageUrl = "https://images.unsplash.com/photo-1605733513549-de9b150bd70d?w=500&q=80",
                            Name = "Knee High Boot",
                            Price = 118.49m
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 2,
                            Description = "Elegant Peep Toe perfect for any occasion.",
                            ImageUrl = "https://images.unsplash.com/photo-1534653299134-96a171b61581?w=500&q=80",
                            Name = "Peep Toe",
                            Price = 119.99m
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 2,
                            Description = "Elegant Mary Jane perfect for any occasion.",
                            ImageUrl = "https://images.unsplash.com/photo-1553808373-b2c5b7ddb117?w=500&q=80",
                            Name = "Mary Jane",
                            Price = 121.49m
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 3,
                            Description = "Durable Velcro Sneaker for active kids.",
                            ImageUrl = "https://images.unsplash.com/photo-1507464098880-e367bc5d2c08?w=500&q=80",
                            Name = "Velcro Sneaker",
                            Price = 71.99m
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 3,
                            Description = "Durable Light-up Runner for active kids.",
                            ImageUrl = "https://images.unsplash.com/photo-1540479859555-17af45c78602?w=500&q=80",
                            Name = "Light-up Runner",
                            Price = 72.99m
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 3,
                            Description = "Durable School Shoe for active kids.",
                            ImageUrl = "https://images.unsplash.com/photo-1574946943172-4800feadfab7?w=500&q=80",
                            Name = "School Shoe",
                            Price = 73.99m
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 3,
                            Description = "Durable Rain Boot for active kids.",
                            ImageUrl = "https://images.unsplash.com/photo-1584564515943-b54cbb61836b?w=500&q=80",
                            Name = "Rain Boot",
                            Price = 74.99m
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 3,
                            Description = "Durable Summer Sandal for active kids.",
                            ImageUrl = "https://images.unsplash.com/photo-1552912276-56ef47874741?w=500&q=80",
                            Name = "Summer Sandal",
                            Price = 75.99m
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 3,
                            Description = "Durable Winter Boot for active kids.",
                            ImageUrl = "https://images.unsplash.com/photo-1507464098880-e367bc5d2c08?w=500&q=80",
                            Name = "Winter Boot",
                            Price = 76.99m
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 3,
                            Description = "Durable Sporty Trainer for active kids.",
                            ImageUrl = "https://images.unsplash.com/photo-1540479859555-17af45c78602?w=500&q=80",
                            Name = "Sporty Trainer",
                            Price = 77.99m
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 3,
                            Description = "Durable Canvas Slip-on for active kids.",
                            ImageUrl = "https://images.unsplash.com/photo-1574946943172-4800feadfab7?w=500&q=80",
                            Name = "Canvas Slip-on",
                            Price = 78.99m
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 3,
                            Description = "Durable Party Shoe for active kids.",
                            ImageUrl = "https://images.unsplash.com/photo-1584564515943-b54cbb61836b?w=500&q=80",
                            Name = "Party Shoe",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 3,
                            Description = "Durable Indoor Slipper for active kids.",
                            ImageUrl = "https://images.unsplash.com/photo-1552912276-56ef47874741?w=500&q=80",
                            Name = "Indoor Slipper",
                            Price = 80.99m
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 3,
                            Description = "Durable Soccer Cleat for active kids.",
                            ImageUrl = "https://images.unsplash.com/photo-1507464098880-e367bc5d2c08?w=500&q=80",
                            Name = "Soccer Cleat",
                            Price = 81.99m
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 3,
                            Description = "Durable High Top for active kids.",
                            ImageUrl = "https://images.unsplash.com/photo-1540479859555-17af45c78602?w=500&q=80",
                            Name = "High Top",
                            Price = 82.99m
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 3,
                            Description = "Durable Character Shoe for active kids.",
                            ImageUrl = "https://images.unsplash.com/photo-1574946943172-4800feadfab7?w=500&q=80",
                            Name = "Character Shoe",
                            Price = 83.99m
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 3,
                            Description = "Durable Toddler Walker for active kids.",
                            ImageUrl = "https://images.unsplash.com/photo-1584564515943-b54cbb61836b?w=500&q=80",
                            Name = "Toddler Walker",
                            Price = 84.99m
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 3,
                            Description = "Durable Pre-school Runner for active kids.",
                            ImageUrl = "https://images.unsplash.com/photo-1552912276-56ef47874741?w=500&q=80",
                            Name = "Pre-school Runner",
                            Price = 85.99m
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 3,
                            Description = "Durable Junior Hiker for active kids.",
                            ImageUrl = "https://images.unsplash.com/photo-1507464098880-e367bc5d2c08?w=500&q=80",
                            Name = "Junior Hiker",
                            Price = 86.99m
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 3,
                            Description = "Durable Beach Slide for active kids.",
                            ImageUrl = "https://images.unsplash.com/photo-1540479859555-17af45c78602?w=500&q=80",
                            Name = "Beach Slide",
                            Price = 87.99m
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 3,
                            Description = "Durable Warm Booties for active kids.",
                            ImageUrl = "https://images.unsplash.com/photo-1574946943172-4800feadfab7?w=500&q=80",
                            Name = "Warm Booties",
                            Price = 88.99m
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 3,
                            Description = "Durable Dress Shoe for active kids.",
                            ImageUrl = "https://images.unsplash.com/photo-1584564515943-b54cbb61836b?w=500&q=80",
                            Name = "Dress Shoe",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 3,
                            Description = "Durable Playground Sneaker for active kids.",
                            ImageUrl = "https://images.unsplash.com/photo-1552912276-56ef47874741?w=500&q=80",
                            Name = "Playground Sneaker",
                            Price = 90.99m
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 4,
                            Description = "High-performance Pro Marathoner for serious runners.",
                            ImageUrl = "https://images.unsplash.com/photo-1602190420103-683df5093e86?w=500&q=80",
                            Name = "Pro Marathoner",
                            Price = 244.99m
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 4,
                            Description = "High-performance Sprint Spike for serious runners.",
                            ImageUrl = "https://images.unsplash.com/photo-1581888748626-2a3f240a6f9f?w=500&q=80",
                            Name = "Sprint Spike",
                            Price = 247.49m
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 4,
                            Description = "High-performance Trail Blazer for serious runners.",
                            ImageUrl = "https://images.unsplash.com/photo-1709258228137-19a8c193be39?w=500&q=80",
                            Name = "Trail Blazer",
                            Price = 249.99m
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 4,
                            Description = "High-performance Cushion Cloud for serious runners.",
                            ImageUrl = "https://images.unsplash.com/photo-1597892657493-6847b9640bac?w=500&q=80",
                            Name = "Cushion Cloud",
                            Price = 252.49m
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 4,
                            Description = "High-performance Speed Demon for serious runners.",
                            ImageUrl = "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=500&q=80",
                            Name = "Speed Demon",
                            Price = 254.99m
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 4,
                            Description = "High-performance Endurance Pro for serious runners.",
                            ImageUrl = "https://images.unsplash.com/photo-1602190420103-683df5093e86?w=500&q=80",
                            Name = "Endurance Pro",
                            Price = 257.49m
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 4,
                            Description = "High-performance Morning Jogger for serious runners.",
                            ImageUrl = "https://images.unsplash.com/photo-1581888748626-2a3f240a6f9f?w=500&q=80",
                            Name = "Morning Jogger",
                            Price = 259.99m
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 4,
                            Description = "High-performance Track Star for serious runners.",
                            ImageUrl = "https://images.unsplash.com/photo-1709258228137-19a8c193be39?w=500&q=80",
                            Name = "Track Star",
                            Price = 262.49m
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 4,
                            Description = "High-performance Lite Racer for serious runners.",
                            ImageUrl = "https://images.unsplash.com/photo-1597892657493-6847b9640bac?w=500&q=80",
                            Name = "Lite Racer",
                            Price = 264.99m
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 4,
                            Description = "High-performance Impact Absorber for serious runners.",
                            ImageUrl = "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=500&q=80",
                            Name = "Impact Absorber",
                            Price = 267.49m
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 4,
                            Description = "High-performance Distance Runner for serious runners.",
                            ImageUrl = "https://images.unsplash.com/photo-1602190420103-683df5093e86?w=500&q=80",
                            Name = "Distance Runner",
                            Price = 269.99m
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 4,
                            Description = "High-performance Flex Sole for serious runners.",
                            ImageUrl = "https://images.unsplash.com/photo-1581888748626-2a3f240a6f9f?w=500&q=80",
                            Name = "Flex Sole",
                            Price = 272.49m
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 4,
                            Description = "High-performance Grip Master for serious runners.",
                            ImageUrl = "https://images.unsplash.com/photo-1709258228137-19a8c193be39?w=500&q=80",
                            Name = "Grip Master",
                            Price = 274.99m
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 4,
                            Description = "High-performance Aero Dynamic for serious runners.",
                            ImageUrl = "https://images.unsplash.com/photo-1597892657493-6847b9640bac?w=500&q=80",
                            Name = "Aero Dynamic",
                            Price = 277.49m
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 4,
                            Description = "High-performance Urban Sprinter for serious runners.",
                            ImageUrl = "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=500&q=80",
                            Name = "Urban Sprinter",
                            Price = 279.99m
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 4,
                            Description = "High-performance Night Runner for serious runners.",
                            ImageUrl = "https://images.unsplash.com/photo-1602190420103-683df5093e86?w=500&q=80",
                            Name = "Night Runner",
                            Price = 282.49m
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 4,
                            Description = "High-performance Terrain Master for serious runners.",
                            ImageUrl = "https://images.unsplash.com/photo-1581888748626-2a3f240a6f9f?w=500&q=80",
                            Name = "Terrain Master",
                            Price = 284.99m
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 4,
                            Description = "High-performance Velocity Max for serious runners.",
                            ImageUrl = "https://images.unsplash.com/photo-1709258228137-19a8c193be39?w=500&q=80",
                            Name = "Velocity Max",
                            Price = 287.49m
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 4,
                            Description = "High-performance Pace Setter for serious runners.",
                            ImageUrl = "https://images.unsplash.com/photo-1597892657493-6847b9640bac?w=500&q=80",
                            Name = "Pace Setter",
                            Price = 289.99m
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 4,
                            Description = "High-performance Zoom Elite for serious runners.",
                            ImageUrl = "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=500&q=80",
                            Name = "Zoom Elite",
                            Price = 292.49m
                        });
                });

            modelBuilder.Entity("ShoeZilla.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ShoeZilla.Models.Order", b =>
                {
                    b.HasOne("ShoeZilla.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShoeZilla.Models.OrderItem", b =>
                {
                    b.HasOne("ShoeZilla.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShoeZilla.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShoeZilla.Models.Product", b =>
                {
                    b.HasOne("ShoeZilla.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ShoeZilla.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ShoeZilla.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
